### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/grid-wordpress#108]
We got [user feedback on wordpress.org](https://wordpress.org/support/topic/grid-updates-do-not-refresh-cache-comet-cache-varnish-page-edits-do-update/) that neither comet cache nor varnish flushes when publishing a grid.

Plan would be to trigger a post_save with modification date update so wordpress core can do the flushing hopefully.

**Comment by poetaster** [comment]
I reported this on wordpress. (poetaster) .... latest release does not resolve ;)

**Comment by poetaster** [comment]
I'm reporting for netzpolitik.org. This development and the last bug I submitted break PH's templates, made for netzpolitik.org ... We're willing to pay to get this sped up since our caching system is now no longer that which it has been (first static rendering, then via proxy & varnish) since relaunch. And, we can't update the plugin without breaking the site.

**Comment by EdwardBock** [comment]
@poetaster 

Sorry to hear that. I will look into that now!

**Comment by EdwardBock** [comment]
@poetaster 

With Grid release 1.7.13 we do a post_save with new modification date so [varnish-http-purge](https://github.com/Ipstenu/varnish-http-purge/blob/master/varnish-http-purge.php#L465) should do its job now. I did not look into comet cache but I hope it will wait for post_save action to clear cache too.

Could you please check if v1.7.13 is working for you now?

**Comment by poetaster** [comment]
Works for us with 1.7.13!
